CREATE TABLE FILES(
ID NUMBER,
CONSTRAINT FILE_PK PRIMARY KEY(ID),
FILE_NAME NVARCHAR2(50) NOT NULL,
FILE_FORMAT NVARCHAR2(50) NOT NULL,
FILE_SIZE NUMBER NOT NULL,
STORAGE NUMBER,
CONSTRAINT STORAGE_FK FOREIGN KEY(STORAGE) REFERENCES STORAGE(ID)
);

CREATE SEQUENCE FILE_SEQ INCREMENT BY 1 MAXVALUE 1000 CYCLE;

DROP SEQUENCE ITEM_SEQ;