CREATE TABLE STORAGE(
ID NUMBER,
CONSTRAINT STORAGE_PK PRIMARY KEY(ID),
FORMAT_SUPPORTED NVARCHAR2(50) NOT NULL,
STORAGE_COUNTRY NVARCHAR2(50) NOT NULL,
STORAGE_SIZE NUMBER NOT NULL
);

CREATE SEQUENCE STORAGE_SEQ INCREMENT BY 1 MAXVALUE 1000 CYCLE;

DROP SEQUENCE ITEM_SEQ;